namespace $safeprojectname$.Core
{
    public static partial class AppData
    {
        /// <summary>
        /// Common messages
        /// </summary>
        public static class Messages
        {
         
            /// <summary>
            /// "Entity successfully deleted"
            /// </summary>
            public static string EntitySuccessfullyDeleted => "Entity successfully deleted";

            /// <summary>
            /// "Automatically generated by {0}"
            /// </summary>
            public static string ViewModelFactoryGenerationText => "Automatically generated by {0}";
        }
    }
}
