namespace Calabonga.Microservices.Core
{
    /// <summary>
    /// Architecture infrastructure common symbols
    /// </summary>
    public static partial class AppContracts
    {
        public static class Messages
        {
            /// <summary>
            /// "User not registered in the system"
            /// </summary>
            public static string ViewModelFactoryGeneration => "Automatically generated by {0}";
            

        }
    }
}
