namespace Calabonga.Microservices.Core
{
    /// <summary>
    /// Architecture infrastructure common symbols
    /// </summary>
    public static partial class AppContracts
    {
        public static class Messages
        {
            /// <summary>
            /// "User not registered in the system"
            /// </summary>
            public static string ViewModelFactoryGeneration => "Automatically generated by {0}";
            
            /// <summary>
            /// "Some errors occurred while checking the entity"
            /// </summary>
            public static string EntityValidationException => "Some errors occurred while checking the entity";

            /// <summary>
            /// "Unauthorized access denied"
            /// </summary>
            public static string UnauthorizedException => "Unauthorized access denied";

            /// <summary>
            /// "Object not found"
            /// </summary>
            public static string NotFoundException => "Object not found";

            
            /// <summary>
            /// "Argument null exception"
            /// </summary>
            public static string ArgumentNullException => "Argument null exception";
        }
    }
}
