//global using Calabonga.AuthService.Web.Definitions.Identity;
//global using Calabonga.AuthService.Web.Endpoints.Base;
//global using Calabonga.AuthService.Web.Endpoints.EventItemEndpoints.Queries;
//global using Calabonga.AuthService.Web.Endpoints.EventItemEndpoints.ViewModels;
//global using Calabonga.OperationResults;
//global using Calabonga.UnitOfWork;
//global using MediatR;
//global using FluentValidation;
//global using AutoMapper;
//global using Calabonga.AuthService.Domain;
//global using Calabonga.AuthService.Web.Definitions.Mapping;
//global using Microsoft.AspNetCore.Authorization;
//global using Microsoft.AspNetCore.Mvc;
//global using Calabonga.AuthService.Web.Endpoints.ProfileEndpoints.Queries;
//global using Calabonga.AuthService.Web.Endpoints.ProfileEndpoints.ViewModels;
//global using Calabonga.AuthService.Web.Application.Services;
//global using Calabonga.AuthService.Infrastructure;
//global using Calabonga.Microservices.Core;
//global using IdentityModel;
//global using System.Security.Claims;
//global using Serilog;
//global using System.Text.Json;

namespace Calabonga.AuthService.Web;
