name: Module Nuget

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore 'AspNetCore v7.0/Calabonga.Microservice.Module.Template/Calabonga.Microservice.Module.Template.sln'

      - name: Build the NuGet package
        run: dotnet build 'AspNetCore v7.0\Calabonga.Microservice.Module.Template\Calabonga.Microservice.Module.Template.sln' --configuration Release --output ${{env.DOTNET_ROOT}}\Package

      - name: Publish NuGet Package Calabonga.Microservice.Module
        run: dotnet nuget push ${{env.DOTNET_ROOT}}\Package\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
